package Lexer;

//Lista de tokens de Mingol
public enum MingolToken {
    ADDITION,//
    ALGOL,
    ASSIGN,//
    BEGIN,//
    BY,//
    CHARACTER,//TODO
    COMMA,//
    COMMENT,//
    DECIMAL,
    DIVISION,//
    DO,//
    EOL,//
    ELSE,//
    END,//
    EQ,//
    ETIQUETA,
    FALSE,//
    FI,//
    FOR,//
    FROM,//
    GE,//
    GOTO,//
    GT,//
    IDENT,//
    IF,//
    ILLEGAL,//
    INTEGER,//
    LE,//
    LET,
    LPAREN,//
    LT,//
    MULTIPLICATION,//
    NE,//
    NEGATION,
    NEWLINE,
    OD,//
    PRINT,
    READ,
    REAL,//
    RETURN,//
    RPAREN,//
    SEMICOLON,//
    SKIP,//
    //STREQ,
    //STRGE,
    //STRGT,
    STRING,//
    //STRLE,
    //STRLT,
    //STRNE,
    SUBSTRACTION,//
    THEN,//
    TO,//
    TRUE,//
    TYPETRUE,//TODO
    TYPEFALSE,//TODO
    TYPEINT,//
    TYPESTRING,//
    TYPECHAR,//
    TYPEREAL//
}
