package Lexer;

import java.util.HashMap;
import java.util.Map;

public class Token {

    private MingolToken TokenType;
    private String Literal;

    public Token(MingolToken TokenType, String Literal) {
        this.TokenType = TokenType;
        this.Literal = Literal;
    }

    public MingolToken getTokenType() {
        return TokenType;
    }

    public String getLiteral() {
        return Literal;
    }

    public String Tuple() {
        String result = "Type: " + TokenType + ", Literal: " + Literal;
        return result;
    }

    public static MingolToken LookupTokenType(String literal) {
        //Diccionario con los tokens 
        Map keywords = new HashMap<String, MingolToken>();
        keywords.put("BEGIN", MingolToken.BEGIN);
        keywords.put("BY", MingolToken.BY);
        keywords.put("CHAR", MingolToken.TYPECHAR);
        keywords.put("CO", MingolToken.COMMENT);
        keywords.put("COMMENT", MingolToken.COMMENT);
        keywords.put("DO", MingolToken.DO);
        keywords.put("ELSE", MingolToken.ELSE);
        keywords.put("END", MingolToken.END);
        keywords.put("EQ", MingolToken.EQ);
        keywords.put("FALSE", MingolToken.FALSE);
        keywords.put("FI", MingolToken.FI);
        keywords.put("FOR", MingolToken.FOR);
        keywords.put("FROM", MingolToken.FROM);
        keywords.put("GE", MingolToken.GE);
        keywords.put("GOTO", MingolToken.GOTO);
        keywords.put("GT", MingolToken.GT);
        keywords.put("IF", MingolToken.IF);
        keywords.put("INT", MingolToken.TYPEINT);
        keywords.put("LE", MingolToken.LE);
        keywords.put("LT", MingolToken.LT);
        keywords.put("NE", MingolToken.NE);
        keywords.put("OD", MingolToken.OD);
        keywords.put("print", MingolToken.PRINT);
        keywords.put("read", MingolToken.READ);
        keywords.put("REAL", MingolToken.TYPEREAL);
        keywords.put("RETURN", MingolToken.RETURN);
        keywords.put("SKIP", MingolToken.SKIP);
        keywords.put("STRING", MingolToken.TYPESTRING);
        keywords.put("THEN", MingolToken.THEN);
        keywords.put("TO", MingolToken.TO);
        keywords.put("TRUE", MingolToken.TRUE);
//        keywords.put("newline", MingolToken.NEWLINE);
        //ALGOL TOKENS
        keywords.put("",MingolToken.ALGOL);
        keywords.put("ABS", MingolToken.ALGOL);
        keywords.put("AND", MingolToken.ALGOL);
        keywords.put("ARG", MingolToken.ALGOL);
        keywords.put("BIN", MingolToken.ALGOL);
        keywords.put("BITS", MingolToken.ALGOL);
        keywords.put("BOOL", MingolToken.ALGOL);
        keywords.put("BYTES", MingolToken.ALGOL);
        keywords.put("CHANNEL", MingolToken.ALGOL);
        keywords.put("COMPL", MingolToken.ALGOL);
        keywords.put("COMPLEX", MingolToken.ALGOL);
        keywords.put("CONJ", MingolToken.ALGOL);
        keywords.put("DET", MingolToken.ALGOL);
        keywords.put("DIVAB", MingolToken.ALGOL);
        keywords.put("DOUBLE", MingolToken.ALGOL);
        keywords.put("DOWN",MingolToken.ALGOL);
        keywords.put("DYAD",MingolToken.ALGOL);
        keywords.put("ELEM",MingolToken.ALGOL);
        keywords.put("ELSIF",MingolToken.ALGOL);
        keywords.put("ENTRIER",MingolToken.ALGOL);
        keywords.put("FILE", MingolToken.ALGOL);
        keywords.put("FLEX",MingolToken.ALGOL);
        keywords.put("FORMAT",MingolToken.ALGOL);
        keywords.put("IM",MingolToken.ALGOL);
        keywords.put("INV",MingolToken.ALGOL);
        keywords.put("LENG",MingolToken.ALGOL);
        keywords.put("LIBRARY",MingolToken.ALGOL);
        keywords.put("LONG",MingolToken.ALGOL);
        keywords.put("LWB",MingolToken.ALGOL);
        keywords.put("MINUSAB",MingolToken.ALGOL);
        keywords.put("MOD",MingolToken.ALGOL);
        keywords.put("MODAB",MingolToken.ALGOL);
        keywords.put("MODE",MingolToken.ALGOL);
        keywords.put("NIL",MingolToken.ALGOL);
        keywords.put("NORM",MingolToken.ALGOL);
        keywords.put("NOT",MingolToken.ALGOL);
        keywords.put("ODD",MingolToken.ALGOL);
        keywords.put("OP",MingolToken.ALGOL);
        keywords.put("OR",MingolToken.ALGOL);
        keywords.put("OVER",MingolToken.ALGOL);
        keywords.put("OVERAB",MingolToken.ALGOL);
        keywords.put("PIPE",MingolToken.ALGOL);
        keywords.put("PLUSAB",MingolToken.ALGOL);
        keywords.put("PLUSTO",MingolToken.ALGOL);
        keywords.put("PR",MingolToken.ALGOL);
        keywords.put("PRAGMA",MingolToken.ALGOL);
        keywords.put("PRELUDE",MingolToken.ALGOL);
        keywords.put("PRIO",MingolToken.ALGOL);
        keywords.put("PROC",MingolToken.ALGOL);
        keywords.put("RE",MingolToken.ALGOL);
        keywords.put("REF",MingolToken.ALGOL);
        keywords.put("REPEAT", MingolToken.ALGOL);
        keywords.put("REPR",MingolToken.ALGOL);
        keywords.put("ROUND",MingolToken.ALGOL);
        keywords.put("ROW",MingolToken.ALGOL);
        keywords.put("RETURN",MingolToken.ALGOL);
        keywords.put("SEMA",MingolToken.ALGOL);
        keywords.put("SHL",MingolToken.ALGOL);
        keywords.put("SHORT",MingolToken.ALGOL);
        keywords.put("SHORTEN",MingolToken.ALGOL);
        keywords.put("SHR",MingolToken.ALGOL);
        keywords.put("SIGN",MingolToken.ALGOL);
        keywords.put("SOUND",MingolToken.ALGOL);
        keywords.put("STANDARD",MingolToken.ALGOL);
        keywords.put("STRUCT",MingolToken.ALGOL);
        keywords.put("TIMESAB",MingolToken.ALGOL);
        keywords.put("TRACE",MingolToken.ALGOL);
        keywords.put("TRANSPUT",MingolToken.ALGOL);
        keywords.put("UP",MingolToken.ALGOL);
        keywords.put("UPB",MingolToken.ALGOL);
        keywords.put("VOID",MingolToken.ALGOL);
        keywords.put("WHILE",MingolToken.ALGOL);
        keywords.put("XOR",MingolToken.ALGOL);
        keywords.put("a68g",MingolToken.ALGOL);
        keywords.put("abend",MingolToken.ALGOL);
        keywords.put("abort",MingolToken.ALGOL);
        keywords.put("abs",MingolToken.ALGOL);
        keywords.put("airy",MingolToken.ALGOL);
        keywords.put("alnum",MingolToken.ALGOL);
        keywords.put("alpha",MingolToken.ALGOL);
        keywords.put("angle",MingolToken.ALGOL);
        keywords.put("arccos",MingolToken.ALGOL);
        keywords.put("arccosh",MingolToken.ALGOL);
        keywords.put("arcsin",MingolToken.ALGOL);
        keywords.put("arcsinh",MingolToken.ALGOL);
        keywords.put("arctan",MingolToken.ALGOL);
        keywords.put("arctan2",MingolToken.ALGOL);
        keywords.put("arctanh",MingolToken.ALGOL);
        keywords.put("argc",MingolToken.ALGOL);
        keywords.put("argv",MingolToken.ALGOL);
        keywords.put("aspect",MingolToken.ALGOL);
        keywords.put("associate",MingolToken.ALGOL);
        keywords.put("back",MingolToken.ALGOL);
        keywords.put("background",MingolToken.ALGOL);
        keywords.put("backspace",MingolToken.ALGOL);
        keywords.put("bessel",MingolToken.ALGOL);
        keywords.put("beta",MingolToken.ALGOL);
        keywords.put("bin",MingolToken.ALGOL);
        keywords.put("blank",MingolToken.ALGOL);
        keywords.put("break",MingolToken.ALGOL);
        keywords.put("channel",MingolToken.ALGOL);
        keywords.put("cholesky",MingolToken.ALGOL);
        keywords.put("circle",MingolToken.ALGOL);
        keywords.put("clear",MingolToken.ALGOL);
        keywords.put("clock",MingolToken.ALGOL);
        keywords.put("close",MingolToken.ALGOL);
        keywords.put("cntrl",MingolToken.ALGOL);
        keywords.put("collect",MingolToken.ALGOL);
        keywords.put("collections",MingolToken.ALGOL);
        keywords.put("colour",MingolToken.ALGOL);
        keywords.put("columns",MingolToken.ALGOL);
        keywords.put("cos",MingolToken.ALGOL);
        keywords.put("cosh",MingolToken.ALGOL);
        keywords.put("cpu",MingolToken.ALGOL);
        keywords.put("create",MingolToken.ALGOL);
        keywords.put("curses",MingolToken.ALGOL);
        keywords.put("curt",MingolToken.ALGOL);
        keywords.put("debug",MingolToken.ALGOL);
        keywords.put("digit",MingolToken.ALGOL);
        keywords.put("draw",MingolToken.ALGOL);
        keywords.put("elliptic",MingolToken.ALGOL);
        keywords.put("eof",MingolToken.ALGOL);
        keywords.put("eoln",MingolToken.ALGOL);
        keywords.put("erase",MingolToken.ALGOL);
        keywords.put("erf",MingolToken.ALGOL);
        keywords.put("error",MingolToken.ALGOL);
        keywords.put("establish",MingolToken.ALGOL);
        keywords.put("evaluate",MingolToken.ALGOL);
        keywords.put("execve",MingolToken.ALGOL);
        keywords.put("exp",MingolToken.ALGOL);
        keywords.put("factorial",MingolToken.ALGOL);
        keywords.put("fft",MingolToken.ALGOL);
        keywords.put("fill",MingolToken.ALGOL);
        keywords.put("fixed",MingolToken.ALGOL);
        keywords.put("flip",MingolToken.ALGOL);
        keywords.put("float",MingolToken.ALGOL);
        keywords.put("flop",MingolToken.ALGOL);
        keywords.put("font",MingolToken.ALGOL);
        keywords.put("fork",MingolToken.ALGOL);
        keywords.put("format",MingolToken.ALGOL);
        keywords.put("gamma",MingolToken.ALGOL);
        keywords.put("garbage",MingolToken.ALGOL);
        keywords.put("gc",MingolToken.ALGOL);
        keywords.put("get",MingolToken.ALGOL);
        keywords.put("getchar",MingolToken.ALGOL);
        keywords.put("getf",MingolToken.ALGOL);
        keywords.put("graph",MingolToken.ALGOL);
        keywords.put("halt",MingolToken.ALGOL);
        keywords.put("heap",MingolToken.ALGOL);
        keywords.put("http",MingolToken.ALGOL);
        keywords.put("idf",MingolToken.ALGOL);
        keywords.put("in",MingolToken.ALGOL);
        keywords.put("incomplete",MingolToken.ALGOL);
        keywords.put("integral",MingolToken.ALGOL);
        keywords.put("inverse",MingolToken.ALGOL);
        keywords.put("is",MingolToken.ALGOL);
        keywords.put("last",MingolToken.ALGOL);
        keywords.put("lenghts",MingolToken.ALGOL);
        keywords.put("line",MingolToken.ALGOL);
        keywords.put("linestyle",MingolToken.ALGOL);
        keywords.put("linewidth",MingolToken.ALGOL);
        keywords.put("ln",MingolToken.ALGOL);
        keywords.put("local",MingolToken.ALGOL);
        keywords.put("lock",MingolToken.ALGOL);
        keywords.put("log",MingolToken.ALGOL);
        keywords.put("lower",MingolToken.ALGOL);
        keywords.put("lu",MingolToken.ALGOL);
        keywords.put("make",MingolToken.ALGOL);
        keywords.put("max",MingolToken.ALGOL);
        keywords.put("min",MingolToken.ALGOL);
        keywords.put("mksa",MingolToken.ALGOL);
        keywords.put("modes",MingolToken.ALGOL);
        keywords.put("move",MingolToken.ALGOL);
        keywords.put("name",MingolToken.ALGOL);
        keywords.put("new",MingolToken.ALGOL);
        keywords.put("null",MingolToken.ALGOL);
        keywords.put("num",MingolToken.ALGOL);
        keywords.put("on",MingolToken.ALGOL);
        keywords.put("open",MingolToken.ALGOL);
        keywords.put("out",MingolToken.ALGOL);
        keywords.put("pack",MingolToken.ALGOL);
        keywords.put("page",MingolToken.ALGOL);
        keywords.put("pi",MingolToken.ALGOL);
        keywords.put("point",MingolToken.ALGOL);
        keywords.put("pointer",MingolToken.ALGOL);
        keywords.put("possible",MingolToken.ALGOL);
        keywords.put("preemptive",MingolToken.ALGOL);
        keywords.put("print",MingolToken.ALGOL);
        keywords.put("printf",MingolToken.ALGOL);
        keywords.put("punct",MingolToken.ALGOL);
        keywords.put("put",MingolToken.ALGOL);
        keywords.put("putchar",MingolToken.ALGOL);
        keywords.put("putf",MingolToken.ALGOL);
        keywords.put("qr",MingolToken.ALGOL);
        keywords.put("random",MingolToken.ALGOL);
        keywords.put("read",MingolToken.ALGOL);
        keywords.put("rect",MingolToken.ALGOL);
        keywords.put("refresh",MingolToken.ALGOL);
        keywords.put("reidf",MingolToken.ALGOL);
        keywords.put("reset",MingolToken.ALGOL);
        keywords.put("resolution",MingolToken.ALGOL);
        keywords.put("return",MingolToken.ALGOL);
        keywords.put("routine",MingolToken.ALGOL);
        keywords.put("scratch",MingolToken.ALGOL);
        keywords.put("seconds",MingolToken.ALGOL);
        keywords.put("set",MingolToken.ALGOL);
        keywords.put("shorths",MingolToken.ALGOL);
        keywords.put("show",MingolToken.ALGOL);
        keywords.put("sin",MingolToken.ALGOL);
        keywords.put("sinh",MingolToken.ALGOL);
        keywords.put("size",MingolToken.ALGOL);
        keywords.put("size=INT",MingolToken.ALGOL); //?????????
        keywords.put("small",MingolToken.ALGOL);
        keywords.put("sound",MingolToken.ALGOL);
        keywords.put("space",MingolToken.ALGOL);
        keywords.put("sqrt",MingolToken.ALGOL);
        keywords.put("stack",MingolToken.ALGOL);
        keywords.put("stand",MingolToken.ALGOL);
        keywords.put("stop",MingolToken.ALGOL);
        keywords.put("style",MingolToken.ALGOL);
        keywords.put("sub",MingolToken.ALGOL);
        keywords.put("sv",MingolToken.ALGOL);
        keywords.put("sweep",MingolToken.ALGOL);
        keywords.put("system",MingolToken.ALGOL);
        keywords.put("tan",MingolToken.ALGOL);
        keywords.put("tanh",MingolToken.ALGOL);
        keywords.put("tcp",MingolToken.ALGOL);
        keywords.put("term",MingolToken.ALGOL);
        keywords.put("text",MingolToken.ALGOL);
        keywords.put("time",MingolToken.ALGOL);
        keywords.put("upper",MingolToken.ALGOL);
        keywords.put("value",MingolToken.ALGOL);
        keywords.put("wait",MingolToken.ALGOL);
        keywords.put("whole",MingolToken.ALGOL);
        keywords.put("width",MingolToken.ALGOL);
        keywords.put("will",MingolToken.ALGOL);
        keywords.put("window",MingolToken.ALGOL);
        keywords.put("write",MingolToken.ALGOL);
        keywords.put("xdigit",MingolToken.ALGOL);

        MingolToken elToken = (MingolToken) keywords.get(literal);
        if (elToken != null) {
            return elToken;
        } else {
            return MingolToken.IDENT;
        }
    }
}